added new tables

diff --git a/.github/workflows/updated-deploymet.yml b/.github/workflows/updated-deploymet.yml
--- a/.github/workflows/updated-deploymet.yml
+++ b/.github/workflows/updated-deploymet.yml
@@ -40,11 +40,11 @@ jobs:
       # Configure AWS Credentials
       # =====================================================
 
-      - name: Configure AWS credentials using GitHub OIDC
-        uses: aws-actions/configure-aws-credentials@v3
-        with:
-          role-to-assume: arn:aws:iam::054276329279:role/github-actions-oidc-role
-          aws-region: us-east-1
+      # - name: Configure AWS credentials using GitHub OIDC
+      #   uses: aws-actions/configure-aws-credentials@v3
+      #   with:
+      #     role-to-assume: arn:aws:iam::054276329279:role/github-actions-oidc-role
+      #     aws-region: us-east-1
 
       # =====================================================
       # Debug Environment
@@ -69,42 +69,42 @@ jobs:
             exit 1
           }
 
-      # =====================================================
-      # Check Deployment Lock
-      # =====================================================
+      # # =====================================================
+      # # Check Deployment Lock
+      # # =====================================================
 
-      - name: Check Deployment Lock
-        shell: powershell
-        run: |
+      # - name: Check Deployment Lock
+      #   shell: powershell
+      #   run: |
 
-          $branch = "${{ github.ref_name }}"
+      #     $branch = "${{ github.ref_name }}"
 
-          $result = aws dynamodb get-item `
-            --table-name deployment_lock `
-            --key "{\""branch_name\"": {\""S\"": \""$branch\""}}"
+      #     $result = aws dynamodb get-item `
+      #       --table-name deployment_lock `
+      #       --key "{\""branch_name\"": {\""S\"": \""$branch\""}}"
 
-          Write-Host ""
-          Write-Host "===== DEPLOYMENT LOCK STATUS ====="
+      #     Write-Host ""
+      #     Write-Host "===== DEPLOYMENT LOCK STATUS ====="
 
-          Write-Host $result
+      #     Write-Host $result
 
-          if ($result -match "LOCKED") {
+      #     if ($result -match "LOCKED") {
 
-            Write-Host ""
-            Write-Host "================================================="
-            Write-Host "DEPLOYMENT LOCK DETECTED"
-            Write-Host "================================================="
-            Write-Host ""
-            Write-Host "Previous deployment failed."
-            Write-Host "Partial deployment may exist."
-            Write-Host "Manual intervention required."
-            Write-Host ""
+      #       Write-Host ""
+      #       Write-Host "================================================="
+      #       Write-Host "DEPLOYMENT LOCK DETECTED"
+      #       Write-Host "================================================="
+      #       Write-Host ""
+      #       Write-Host "Previous deployment failed."
+      #       Write-Host "Partial deployment may exist."
+      #       Write-Host "Manual intervention required."
+      #       Write-Host ""
 
-            exit 1
-          }
+      #       exit 1
+      #     }
 
-          Write-Host ""
-          Write-Host "No deployment lock found."
+      #     Write-Host ""
+      #     Write-Host "No deployment lock found."
 
 
           # =====================================================
@@ -180,33 +180,22 @@ jobs:
       # Generate release.sql Using Python
       # =====================================================
 
-      # - name: Set up Python
-      #   uses: actions/setup-python@v5
-      #   with:
-      #     python-version: '3.13'
-
-      # - name: Generate release.sql
-      #   shell: powershell
-      #   run: |
-
-      #     python database/app_schema/scripts/generate_release.py
-
-      #     Write-Host ""
-      #     Write-Host "===== GENERATED release.sql ====="
-
-      #     Get-Content release.sql
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
 
       - name: Generate release.sql
         shell: powershell
         run: |
 
-          & "C:\Users\Lenovo\AppData\Local\Python\pythoncore-3.14-64\python.exe" `
-            database/app_schema/scripts/generate_release.py
+          python database/app_schema/scripts/generate_release.py
 
           Write-Host ""
           Write-Host "===== GENERATED release.sql ====="
 
           Get-Content release.sql
+
       # =====================================================
       # Execute Deployment
       # =====================================================
@@ -237,29 +226,29 @@ jobs:
       # Create Deployment Lock On Failure
       # =====================================================
 
-      - name: Create Deployment Lock
-        if: failure()
-        shell: powershell
-        run: |
+      # - name: Create Deployment Lock
+      #   if: failure()
+      #   shell: powershell
+      #   run: |
 
-          $branch = "${{ github.ref_name }}"
+      #     $branch = "${{ github.ref_name }}"
 
-          Write-Host ""
-          Write-Host "================================================="
-          Write-Host "CREATING DEPLOYMENT LOCK"
-          Write-Host "================================================="
+      #     Write-Host ""
+      #     Write-Host "================================================="
+      #     Write-Host "CREATING DEPLOYMENT LOCK"
+      #     Write-Host "================================================="
 
-          aws dynamodb put-item `
-            --table-name deployment_lock `
-            --item "{
-              \""branch_name\"": {\""S\"": \""$branch\""},
-              \""lock_status\"": {\""S\"": \""LOCKED\""},
-              \""failed_commit\"": {\""S\"": \""${{ github.sha }}\""},
-              \""workflow_url\"": {\""S\"": \""${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\""}
-            }"
+      #     aws dynamodb put-item `
+      #       --table-name deployment_lock `
+      #       --item "{
+      #         \""branch_name\"": {\""S\"": \""$branch\""},
+      #         \""lock_status\"": {\""S\"": \""LOCKED\""},
+      #         \""failed_commit\"": {\""S\"": \""${{ github.sha }}\""},
+      #         \""workflow_url\"": {\""S\"": \""${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\""}
+      #       }"
 
-          Write-Host ""
-          Write-Host "Deployment lock created in DynamoDB."
+      #     Write-Host ""
+      #     Write-Host "Deployment lock created in DynamoDB."
 
     #   # =====================================================
     #   # Compile Invalid Objects
